In [1]:
import pandas as pd
import matplotlib as plt

In [4]:
df = pd.read_csv('data/2021-22/players_raw.csv',encoding = 'utf-8')

,assists,bonus,bps,chance_of_playing_next_round,chance_of_playing_this_round,clean_sheets,code,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,cost_change_event,...,threat_rank_type,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,yellow_cards
0,0,0,69,100,100,1,80201,None,NaN,0,...,60,10,80974,0,205566,0,0.0,2.2,Leno,0
1,0,0,0,0,0,0,115918,None,NaN,0,...,19,0,19017,0,81363,0,0.0,0.0,Rúnarsson,0
2,0,0,0,0,0,0,47431,None,NaN,0,...,307,0,914,0,20541,0,0.0,0.0,Willian,0
3,1,7,131,0,0,6,54694,None,NaN,0,...,25,44,742898,0,900060,0,0.0,4.6,Aubameyang,3
4,1,3,292,100,100,3,58822,2,NaN,0,...,105,48,66997,0,55154,0,0.8,11.4,Cédric,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,0,0,0,0,0,0,428610,None,NaN,0,...,256,0,612,0,546,0,0.0,0.0,Jordão,0
733,0,0,52,None,None,0,510362,None,NaN,0,...,143,6,696,0,558,0,0.1,1.4,Toti,1
734,0,0,0,0,0,0,225000,None,NaN,0,...,193,0,241,0,196,0,0.0,0.0,Sanderson,0
735,0,0,0,0,0,0,232351,None,NaN,0,...,251,0,86,0,62,0,0.0,0.0,Giles,0
736,3,2,67,None,None,0,510363,None,NaN,0,...,146,20,2256,0,1393,0,0.4,3.6,Chiquinho,0